from setuptools import setup, find_packages

setup(
    name="kronos-finance",
    version="0.1.0",
    description="Kronos Foundation Model for Financial Markets",
    author="NeoQuasar",
    author_email="info@neoquasar.ai",
    packages=find_packages(),
    install_requires=[
        "torch>=1.12.0",
        "transformers>=4.20.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "yfinance>=0.1.70",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "tqdm>=4.62.0",
        "pyyaml>=6.0",
        "accelerate>=0.15.0",
        "datasets>=2.0.0",
        "evaluate>=0.4.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)